import Navbar from '@/components/Navbar/Nav-link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function DashLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Navbar />
      {children}
    </div>
  );
}
